feature: Add support for native PT DDP distribution
aws/sagemaker-pytorch-training-toolkit pull request #236
Opened 2022-07-10 23:49 UTC by vishwakaria

*Issue #, if available:*

*Description of changes:*
* Allow customers to launch native PTDDP jobs with `nccl` backend using a new distribution value: `{ "pytorchddp": "enabled": "true",  <other options> }}`
* Uses smdataparallel runner for launch, same as smdistributed backend.
* [Design document](https://quip-amazon.com/XqmTAXW29Nua/Improving-Launcher-experience-on-SageMaker)
* [Testing information](https://quip-amazon.com/usIaAMvBbknO/Test-Plan-PT-DDP-Launcher)
* Connected PRs: <TBA>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-26 10:22 UTC, satishpasumarthi requested changes
Please squash any unnecessary commits. Also follow the commit message structure according to:
https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md#committing-your-change

2022-07-27 17:26 UTC, satishpasumarthi approved these changes
LGTM !

2022-07-29 00:34 UTC, nish21 submitted a review, later dismissed

2022-07-29 21:38 UTC, nish21 approved these changes

2022-07-29 21:41 UTC, merged